### ISSUE TITLE
Use the minified angular files when requiring via napa

### ISSUE THREAD

**Issue by mikekidder** [twilson63/angular-browserify-example#1]
Hi Tom,   I didn't see it mentioned anywhere.  You can require the minified version in your app.js file like so:

```
require('angular/angular.min');
require('angular-route/angular-route.min');
```

It shaves about 700kb off your bundle.js file from your example.

**Comment by twilson63** [comment]
Nice!

I did not know you could include the min version, I usually send the whole
bundle.js through uglify in production.

Thanks for the advice!

Tom

On Wed, Jun 18, 2014 at 11:42 PM, Mike Kidder notifications@github.com
wrote:

> Hi Tom, I didn't see it mentioned anywhere. You can require the minified
> version in your app.js file like so:
> 
> require('angular/angular.min');
> require('angular-route/angular-route.min');
> 
> It shaves about 700kb off your bundle.js file from your example.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/twilson63/angular-browserify-example/issues/1.

## 

Tom Wilson
Jack Russell Software Company Division of CareKinesis
494 Wando Park Blvd
Mount Pleasant, SC  29464
Phone: 843-606-6484
Mobile: 843-469-5856
Email: tom@jackhq.com
Web: http://www.jackhq.com
Calendar:
http://www.google.com/calendar/embed?src=tom%40jackrussellsoftware.com&ctz=America/New_York
http://www.jackhq.com/calendar

This e-mail may contain information that is confidential, privileged or
otherwise protected from disclosure by the Health Insurance Portability and
Accountability Act (HIPAA) and other state and federal laws.  This
information is intended only for the individual names above.  Any review,
use disclosure or dissemination of this material is strictly prohibited.
If you receive this information in error, please notify CareKinesis
immediately at 888-974-2763 and delete the original at once.

**Comment by mikekidder** [comment]
No problem, it works as you're basically requiring via a file path at this point.  Those .min files have a reference to their .map files, so still possible to step through for debugging if needed.

I've tested the minified files with uglifyjs

```
"build-prod" : "browserify -t brfs app/app.js | uglifyjs > public/bundle.js"
```

and you get about another 10kb of compression (remove whitespace, references to .map files, etc).
